#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDog
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db1449f357b50747b19f25a1b200c3ba4b")]
	public partial class DOGDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDealerInventoryCICO(DealerInventoryCICO instance);
    partial void UpdateDealerInventoryCICO(DealerInventoryCICO instance);
    partial void DeleteDealerInventoryCICO(DealerInventoryCICO instance);
    partial void InsertDealerTagTable(DealerTagTable instance);
    partial void UpdateDealerTagTable(DealerTagTable instance);
    partial void DeleteDealerTagTable(DealerTagTable instance);
    partial void InsertContact(Contact instance);
    partial void UpdateContact(Contact instance);
    partial void DeleteContact(Contact instance);
    partial void InsertVendor(Vendor instance);
    partial void UpdateVendor(Vendor instance);
    partial void DeleteVendor(Vendor instance);
    #endregion
		
		public DOGDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DeviceonguardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DOGDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DOGDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DOGDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DOGDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DealerInventoryCICO> DealerInventoryCICOs
		{
			get
			{
				return this.GetTable<DealerInventoryCICO>();
			}
		}
		
		public System.Data.Linq.Table<DealerTagTable> DealerTagTables
		{
			get
			{
				return this.GetTable<DealerTagTable>();
			}
		}
		
		public System.Data.Linq.Table<Contact> Contacts
		{
			get
			{
				return this.GetTable<Contact>();
			}
		}
		
		public System.Data.Linq.Table<Vendor> Vendors
		{
			get
			{
				return this.GetTable<Vendor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DealerInventoryCICO")]
	public partial class DealerInventoryCICO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DealerInventoryCICOID;
		
		private System.Nullable<int> _DealerInventoryID;
		
		private System.Nullable<int> _CheckOutEmployeeID;
		
		private System.Nullable<System.DateTime> _CheckOutDateTime;
		
		private string _CheckOutKeyRFid;
		
		private System.Nullable<System.DateTime> _CheckOutKeyDateTime;
		
		private string _CheckOutDealerTagRFid;
		
		private System.Nullable<System.DateTime> _CheckOutDealerTagDateTime;
		
		private System.Nullable<int> _CheckOutDealerTagID;
		
		private string _CheckOutReason;
		
		private System.Nullable<int> _CheckOutContactID;
		
		private System.Nullable<int> _CheckOutVendorID;
		
		private System.Nullable<int> _CheckOutMileage;
		
		private System.Nullable<int> _CheckOutMilesPermitted;
		
		private System.Nullable<int> _CheckOutHoursPermitted;
		
		private System.Nullable<int> _CheckInEmployeeID;
		
		private System.Nullable<System.DateTime> _CheckInDateTime;
		
		private string _CheckInKeyRFid;
		
		private System.Nullable<System.DateTime> _CheckInKeyDateTime;
		
		private string _CheckInDealerTagRFid;
		
		private System.Nullable<System.DateTime> _CheckInDealerTagDateTime;
		
		private System.Nullable<int> _CheckInMileage;
		
		private string _CheckInResult;
		
		private string _CheckInLicensePlateSold;
		
		private string _CheckInNotes;
		
		private System.Nullable<System.DateTime> _RowDateTime;
		
		private EntityRef<DealerTagTable> _DealerTagTable;
		
		private EntityRef<Contact> _Contact;
		
		private EntityRef<Vendor> _Vendor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDealerInventoryCICOIDChanging(int value);
    partial void OnDealerInventoryCICOIDChanged();
    partial void OnDealerInventoryIDChanging(System.Nullable<int> value);
    partial void OnDealerInventoryIDChanged();
    partial void OnCheckOutEmployeeIDChanging(System.Nullable<int> value);
    partial void OnCheckOutEmployeeIDChanged();
    partial void OnCheckOutDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckOutDateTimeChanged();
    partial void OnCheckOutKeyRFidChanging(string value);
    partial void OnCheckOutKeyRFidChanged();
    partial void OnCheckOutKeyDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckOutKeyDateTimeChanged();
    partial void OnCheckOutDealerTagRFidChanging(string value);
    partial void OnCheckOutDealerTagRFidChanged();
    partial void OnCheckOutDealerTagDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckOutDealerTagDateTimeChanged();
    partial void OnCheckOutDealerTagIDChanging(System.Nullable<int> value);
    partial void OnCheckOutDealerTagIDChanged();
    partial void OnCheckOutReasonChanging(string value);
    partial void OnCheckOutReasonChanged();
    partial void OnCheckOutContactIDChanging(System.Nullable<int> value);
    partial void OnCheckOutContactIDChanged();
    partial void OnCheckOutVendorIDChanging(System.Nullable<int> value);
    partial void OnCheckOutVendorIDChanged();
    partial void OnCheckOutMileageChanging(System.Nullable<int> value);
    partial void OnCheckOutMileageChanged();
    partial void OnCheckOutMilesPermittedChanging(System.Nullable<int> value);
    partial void OnCheckOutMilesPermittedChanged();
    partial void OnCheckOutHoursPermittedChanging(System.Nullable<int> value);
    partial void OnCheckOutHoursPermittedChanged();
    partial void OnCheckInEmployeeIDChanging(System.Nullable<int> value);
    partial void OnCheckInEmployeeIDChanged();
    partial void OnCheckInDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckInDateTimeChanged();
    partial void OnCheckInKeyRFidChanging(string value);
    partial void OnCheckInKeyRFidChanged();
    partial void OnCheckInKeyDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckInKeyDateTimeChanged();
    partial void OnCheckInDealerTagRFidChanging(string value);
    partial void OnCheckInDealerTagRFidChanged();
    partial void OnCheckInDealerTagDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckInDealerTagDateTimeChanged();
    partial void OnCheckInMileageChanging(System.Nullable<int> value);
    partial void OnCheckInMileageChanged();
    partial void OnCheckInResultChanging(string value);
    partial void OnCheckInResultChanged();
    partial void OnCheckInLicensePlateSoldChanging(string value);
    partial void OnCheckInLicensePlateSoldChanged();
    partial void OnCheckInNotesChanging(string value);
    partial void OnCheckInNotesChanged();
    partial void OnRowDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRowDateTimeChanged();
    #endregion
		
		public DealerInventoryCICO()
		{
			this._DealerTagTable = default(EntityRef<DealerTagTable>);
			this._Contact = default(EntityRef<Contact>);
			this._Vendor = default(EntityRef<Vendor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerInventoryCICOID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DealerInventoryCICOID
		{
			get
			{
				return this._DealerInventoryCICOID;
			}
			set
			{
				if ((this._DealerInventoryCICOID != value))
				{
					this.OnDealerInventoryCICOIDChanging(value);
					this.SendPropertyChanging();
					this._DealerInventoryCICOID = value;
					this.SendPropertyChanged("DealerInventoryCICOID");
					this.OnDealerInventoryCICOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerInventoryID", DbType="Int")]
		public System.Nullable<int> DealerInventoryID
		{
			get
			{
				return this._DealerInventoryID;
			}
			set
			{
				if ((this._DealerInventoryID != value))
				{
					this.OnDealerInventoryIDChanging(value);
					this.SendPropertyChanging();
					this._DealerInventoryID = value;
					this.SendPropertyChanged("DealerInventoryID");
					this.OnDealerInventoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutEmployeeID", DbType="Int")]
		public System.Nullable<int> CheckOutEmployeeID
		{
			get
			{
				return this._CheckOutEmployeeID;
			}
			set
			{
				if ((this._CheckOutEmployeeID != value))
				{
					this.OnCheckOutEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._CheckOutEmployeeID = value;
					this.SendPropertyChanged("CheckOutEmployeeID");
					this.OnCheckOutEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckOutDateTime
		{
			get
			{
				return this._CheckOutDateTime;
			}
			set
			{
				if ((this._CheckOutDateTime != value))
				{
					this.OnCheckOutDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckOutDateTime = value;
					this.SendPropertyChanged("CheckOutDateTime");
					this.OnCheckOutDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutKeyRFid", DbType="NVarChar(255)")]
		public string CheckOutKeyRFid
		{
			get
			{
				return this._CheckOutKeyRFid;
			}
			set
			{
				if ((this._CheckOutKeyRFid != value))
				{
					this.OnCheckOutKeyRFidChanging(value);
					this.SendPropertyChanging();
					this._CheckOutKeyRFid = value;
					this.SendPropertyChanged("CheckOutKeyRFid");
					this.OnCheckOutKeyRFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutKeyDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckOutKeyDateTime
		{
			get
			{
				return this._CheckOutKeyDateTime;
			}
			set
			{
				if ((this._CheckOutKeyDateTime != value))
				{
					this.OnCheckOutKeyDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckOutKeyDateTime = value;
					this.SendPropertyChanged("CheckOutKeyDateTime");
					this.OnCheckOutKeyDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutDealerTagRFid", DbType="NVarChar(255)")]
		public string CheckOutDealerTagRFid
		{
			get
			{
				return this._CheckOutDealerTagRFid;
			}
			set
			{
				if ((this._CheckOutDealerTagRFid != value))
				{
					this.OnCheckOutDealerTagRFidChanging(value);
					this.SendPropertyChanging();
					this._CheckOutDealerTagRFid = value;
					this.SendPropertyChanged("CheckOutDealerTagRFid");
					this.OnCheckOutDealerTagRFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutDealerTagDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckOutDealerTagDateTime
		{
			get
			{
				return this._CheckOutDealerTagDateTime;
			}
			set
			{
				if ((this._CheckOutDealerTagDateTime != value))
				{
					this.OnCheckOutDealerTagDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckOutDealerTagDateTime = value;
					this.SendPropertyChanged("CheckOutDealerTagDateTime");
					this.OnCheckOutDealerTagDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutDealerTagID", DbType="Int")]
		public System.Nullable<int> CheckOutDealerTagID
		{
			get
			{
				return this._CheckOutDealerTagID;
			}
			set
			{
				if ((this._CheckOutDealerTagID != value))
				{
					if (this._DealerTagTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckOutDealerTagIDChanging(value);
					this.SendPropertyChanging();
					this._CheckOutDealerTagID = value;
					this.SendPropertyChanged("CheckOutDealerTagID");
					this.OnCheckOutDealerTagIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutReason", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CheckOutReason
		{
			get
			{
				return this._CheckOutReason;
			}
			set
			{
				if ((this._CheckOutReason != value))
				{
					this.OnCheckOutReasonChanging(value);
					this.SendPropertyChanging();
					this._CheckOutReason = value;
					this.SendPropertyChanged("CheckOutReason");
					this.OnCheckOutReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutContactID", DbType="Int")]
		public System.Nullable<int> CheckOutContactID
		{
			get
			{
				return this._CheckOutContactID;
			}
			set
			{
				if ((this._CheckOutContactID != value))
				{
					if (this._Contact.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckOutContactIDChanging(value);
					this.SendPropertyChanging();
					this._CheckOutContactID = value;
					this.SendPropertyChanged("CheckOutContactID");
					this.OnCheckOutContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutVendorID", DbType="Int")]
		public System.Nullable<int> CheckOutVendorID
		{
			get
			{
				return this._CheckOutVendorID;
			}
			set
			{
				if ((this._CheckOutVendorID != value))
				{
					if (this._Vendor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCheckOutVendorIDChanging(value);
					this.SendPropertyChanging();
					this._CheckOutVendorID = value;
					this.SendPropertyChanged("CheckOutVendorID");
					this.OnCheckOutVendorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutMileage", DbType="Int")]
		public System.Nullable<int> CheckOutMileage
		{
			get
			{
				return this._CheckOutMileage;
			}
			set
			{
				if ((this._CheckOutMileage != value))
				{
					this.OnCheckOutMileageChanging(value);
					this.SendPropertyChanging();
					this._CheckOutMileage = value;
					this.SendPropertyChanged("CheckOutMileage");
					this.OnCheckOutMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutMilesPermitted", DbType="Int")]
		public System.Nullable<int> CheckOutMilesPermitted
		{
			get
			{
				return this._CheckOutMilesPermitted;
			}
			set
			{
				if ((this._CheckOutMilesPermitted != value))
				{
					this.OnCheckOutMilesPermittedChanging(value);
					this.SendPropertyChanging();
					this._CheckOutMilesPermitted = value;
					this.SendPropertyChanged("CheckOutMilesPermitted");
					this.OnCheckOutMilesPermittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOutHoursPermitted", DbType="Int")]
		public System.Nullable<int> CheckOutHoursPermitted
		{
			get
			{
				return this._CheckOutHoursPermitted;
			}
			set
			{
				if ((this._CheckOutHoursPermitted != value))
				{
					this.OnCheckOutHoursPermittedChanging(value);
					this.SendPropertyChanging();
					this._CheckOutHoursPermitted = value;
					this.SendPropertyChanged("CheckOutHoursPermitted");
					this.OnCheckOutHoursPermittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInEmployeeID", DbType="Int")]
		public System.Nullable<int> CheckInEmployeeID
		{
			get
			{
				return this._CheckInEmployeeID;
			}
			set
			{
				if ((this._CheckInEmployeeID != value))
				{
					this.OnCheckInEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._CheckInEmployeeID = value;
					this.SendPropertyChanged("CheckInEmployeeID");
					this.OnCheckInEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckInDateTime
		{
			get
			{
				return this._CheckInDateTime;
			}
			set
			{
				if ((this._CheckInDateTime != value))
				{
					this.OnCheckInDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckInDateTime = value;
					this.SendPropertyChanged("CheckInDateTime");
					this.OnCheckInDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInKeyRFid", DbType="NVarChar(255)")]
		public string CheckInKeyRFid
		{
			get
			{
				return this._CheckInKeyRFid;
			}
			set
			{
				if ((this._CheckInKeyRFid != value))
				{
					this.OnCheckInKeyRFidChanging(value);
					this.SendPropertyChanging();
					this._CheckInKeyRFid = value;
					this.SendPropertyChanged("CheckInKeyRFid");
					this.OnCheckInKeyRFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInKeyDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckInKeyDateTime
		{
			get
			{
				return this._CheckInKeyDateTime;
			}
			set
			{
				if ((this._CheckInKeyDateTime != value))
				{
					this.OnCheckInKeyDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckInKeyDateTime = value;
					this.SendPropertyChanged("CheckInKeyDateTime");
					this.OnCheckInKeyDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInDealerTagRFid", DbType="NVarChar(255)")]
		public string CheckInDealerTagRFid
		{
			get
			{
				return this._CheckInDealerTagRFid;
			}
			set
			{
				if ((this._CheckInDealerTagRFid != value))
				{
					this.OnCheckInDealerTagRFidChanging(value);
					this.SendPropertyChanging();
					this._CheckInDealerTagRFid = value;
					this.SendPropertyChanged("CheckInDealerTagRFid");
					this.OnCheckInDealerTagRFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInDealerTagDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckInDealerTagDateTime
		{
			get
			{
				return this._CheckInDealerTagDateTime;
			}
			set
			{
				if ((this._CheckInDealerTagDateTime != value))
				{
					this.OnCheckInDealerTagDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CheckInDealerTagDateTime = value;
					this.SendPropertyChanged("CheckInDealerTagDateTime");
					this.OnCheckInDealerTagDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInMileage", DbType="Int")]
		public System.Nullable<int> CheckInMileage
		{
			get
			{
				return this._CheckInMileage;
			}
			set
			{
				if ((this._CheckInMileage != value))
				{
					this.OnCheckInMileageChanging(value);
					this.SendPropertyChanging();
					this._CheckInMileage = value;
					this.SendPropertyChanged("CheckInMileage");
					this.OnCheckInMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInResult", DbType="NVarChar(255)")]
		public string CheckInResult
		{
			get
			{
				return this._CheckInResult;
			}
			set
			{
				if ((this._CheckInResult != value))
				{
					this.OnCheckInResultChanging(value);
					this.SendPropertyChanging();
					this._CheckInResult = value;
					this.SendPropertyChanged("CheckInResult");
					this.OnCheckInResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInLicensePlateSold", DbType="VarChar(15)")]
		public string CheckInLicensePlateSold
		{
			get
			{
				return this._CheckInLicensePlateSold;
			}
			set
			{
				if ((this._CheckInLicensePlateSold != value))
				{
					this.OnCheckInLicensePlateSoldChanging(value);
					this.SendPropertyChanging();
					this._CheckInLicensePlateSold = value;
					this.SendPropertyChanged("CheckInLicensePlateSold");
					this.OnCheckInLicensePlateSoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInNotes", DbType="NVarChar(255)")]
		public string CheckInNotes
		{
			get
			{
				return this._CheckInNotes;
			}
			set
			{
				if ((this._CheckInNotes != value))
				{
					this.OnCheckInNotesChanging(value);
					this.SendPropertyChanging();
					this._CheckInNotes = value;
					this.SendPropertyChanged("CheckInNotes");
					this.OnCheckInNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RowDateTime
		{
			get
			{
				return this._RowDateTime;
			}
			set
			{
				if ((this._RowDateTime != value))
				{
					this.OnRowDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RowDateTime = value;
					this.SendPropertyChanged("RowDateTime");
					this.OnRowDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DealerTagTable_DealerInventoryCICO", Storage="_DealerTagTable", ThisKey="CheckOutDealerTagID", OtherKey="DealerTagID", IsForeignKey=true)]
		public DealerTagTable DealerTagTable
		{
			get
			{
				return this._DealerTagTable.Entity;
			}
			set
			{
				DealerTagTable previousValue = this._DealerTagTable.Entity;
				if (((previousValue != value) 
							|| (this._DealerTagTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DealerTagTable.Entity = null;
						previousValue.DealerInventoryCICOs.Remove(this);
					}
					this._DealerTagTable.Entity = value;
					if ((value != null))
					{
						value.DealerInventoryCICOs.Add(this);
						this._CheckOutDealerTagID = value.DealerTagID;
					}
					else
					{
						this._CheckOutDealerTagID = default(Nullable<int>);
					}
					this.SendPropertyChanged("DealerTagTable");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contact_DealerInventoryCICO", Storage="_Contact", ThisKey="CheckOutContactID", OtherKey="ContactID", IsForeignKey=true)]
		public Contact Contact
		{
			get
			{
				return this._Contact.Entity;
			}
			set
			{
				Contact previousValue = this._Contact.Entity;
				if (((previousValue != value) 
							|| (this._Contact.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Contact.Entity = null;
						previousValue.DealerInventoryCICOs.Remove(this);
					}
					this._Contact.Entity = value;
					if ((value != null))
					{
						value.DealerInventoryCICOs.Add(this);
						this._CheckOutContactID = value.ContactID;
					}
					else
					{
						this._CheckOutContactID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Contact");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendor_DealerInventoryCICO", Storage="_Vendor", ThisKey="CheckOutVendorID", OtherKey="VendorID", IsForeignKey=true)]
		public Vendor Vendor
		{
			get
			{
				return this._Vendor.Entity;
			}
			set
			{
				Vendor previousValue = this._Vendor.Entity;
				if (((previousValue != value) 
							|| (this._Vendor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendor.Entity = null;
						previousValue.DealerInventoryCICOs.Remove(this);
					}
					this._Vendor.Entity = value;
					if ((value != null))
					{
						value.DealerInventoryCICOs.Add(this);
						this._CheckOutVendorID = value.VendorID;
					}
					else
					{
						this._CheckOutVendorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vendor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DealerTags")]
	public partial class DealerTagTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DealerTagID;
		
		private string _DealerTag;
		
		private string _DealerTagRFid;
		
		private System.Nullable<System.DateTime> _RemoveDate;
		
		private System.Nullable<System.DateTime> _RowDateTime;
		
		private EntitySet<DealerInventoryCICO> _DealerInventoryCICOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDealerTagIDChanging(int value);
    partial void OnDealerTagIDChanged();
    partial void OnDealerTagChanging(string value);
    partial void OnDealerTagChanged();
    partial void OnDealerTagRFidChanging(string value);
    partial void OnDealerTagRFidChanged();
    partial void OnRemoveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRemoveDateChanged();
    partial void OnRowDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRowDateTimeChanged();
    #endregion
		
		public DealerTagTable()
		{
			this._DealerInventoryCICOs = new EntitySet<DealerInventoryCICO>(new Action<DealerInventoryCICO>(this.attach_DealerInventoryCICOs), new Action<DealerInventoryCICO>(this.detach_DealerInventoryCICOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerTagID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DealerTagID
		{
			get
			{
				return this._DealerTagID;
			}
			set
			{
				if ((this._DealerTagID != value))
				{
					this.OnDealerTagIDChanging(value);
					this.SendPropertyChanging();
					this._DealerTagID = value;
					this.SendPropertyChanged("DealerTagID");
					this.OnDealerTagIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerTag", DbType="NVarChar(255)")]
		public string DealerTag
		{
			get
			{
				return this._DealerTag;
			}
			set
			{
				if ((this._DealerTag != value))
				{
					this.OnDealerTagChanging(value);
					this.SendPropertyChanging();
					this._DealerTag = value;
					this.SendPropertyChanged("DealerTag");
					this.OnDealerTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DealerTagRFid", DbType="NVarChar(255)")]
		public string DealerTagRFid
		{
			get
			{
				return this._DealerTagRFid;
			}
			set
			{
				if ((this._DealerTagRFid != value))
				{
					this.OnDealerTagRFidChanging(value);
					this.SendPropertyChanging();
					this._DealerTagRFid = value;
					this.SendPropertyChanged("DealerTagRFid");
					this.OnDealerTagRFidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemoveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RemoveDate
		{
			get
			{
				return this._RemoveDate;
			}
			set
			{
				if ((this._RemoveDate != value))
				{
					this.OnRemoveDateChanging(value);
					this.SendPropertyChanging();
					this._RemoveDate = value;
					this.SendPropertyChanged("RemoveDate");
					this.OnRemoveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RowDateTime
		{
			get
			{
				return this._RowDateTime;
			}
			set
			{
				if ((this._RowDateTime != value))
				{
					this.OnRowDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RowDateTime = value;
					this.SendPropertyChanged("RowDateTime");
					this.OnRowDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DealerTagTable_DealerInventoryCICO", Storage="_DealerInventoryCICOs", ThisKey="DealerTagID", OtherKey="CheckOutDealerTagID")]
		public EntitySet<DealerInventoryCICO> DealerInventoryCICOs
		{
			get
			{
				return this._DealerInventoryCICOs;
			}
			set
			{
				this._DealerInventoryCICOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.DealerTagTable = this;
		}
		
		private void detach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.DealerTagTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Contacts")]
	public partial class Contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContactID;
		
		private string _DLNumber;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private System.Nullable<short> _BirthdayYear;
		
		private string _Sex;
		
		private string _Height;
		
		private string _Address;
		
		private string _City;
		
		private string _StateOrProvince;
		
		private string _PostalCode;
		
		private string _Country;
		
		private string _HomePhone;
		
		private string _EmailAddress;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<int> _Status;
		
		private string _LeadSource;
		
		private System.Nullable<System.DateTime> _LeadOriginalDate;
		
		private string _Company;
		
		private string _JobTitle;
		
		private string _BusinessPhone;
		
		private string _MobilePhone;
		
		private string _FaxNumber;
		
		private string _WebPage;
		
		private string _ContactNotes;
		
		private string _StockNumber;
		
		private string _PreferredVehicleType;
		
		private System.Nullable<int> _PreferredVehicleYear;
		
		private string _PreferredVehicleMake;
		
		private string _PreferredVehicleModel;
		
		private System.Nullable<bool> _ApptSet;
		
		private System.Data.Linq.Binary _upsize_ts;
		
		private System.Nullable<System.DateTime> _RowDateTime;
		
		private EntitySet<DealerInventoryCICO> _DealerInventoryCICOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIDChanging(int value);
    partial void OnContactIDChanged();
    partial void OnDLNumberChanging(string value);
    partial void OnDLNumberChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnBirthdayYearChanging(System.Nullable<short> value);
    partial void OnBirthdayYearChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnHeightChanging(string value);
    partial void OnHeightChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateOrProvinceChanging(string value);
    partial void OnStateOrProvinceChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnHomePhoneChanging(string value);
    partial void OnHomePhoneChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnLeadSourceChanging(string value);
    partial void OnLeadSourceChanged();
    partial void OnLeadOriginalDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLeadOriginalDateChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnBusinessPhoneChanging(string value);
    partial void OnBusinessPhoneChanged();
    partial void OnMobilePhoneChanging(string value);
    partial void OnMobilePhoneChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnWebPageChanging(string value);
    partial void OnWebPageChanged();
    partial void OnContactNotesChanging(string value);
    partial void OnContactNotesChanged();
    partial void OnStockNumberChanging(string value);
    partial void OnStockNumberChanged();
    partial void OnPreferredVehicleTypeChanging(string value);
    partial void OnPreferredVehicleTypeChanged();
    partial void OnPreferredVehicleYearChanging(System.Nullable<int> value);
    partial void OnPreferredVehicleYearChanged();
    partial void OnPreferredVehicleMakeChanging(string value);
    partial void OnPreferredVehicleMakeChanged();
    partial void OnPreferredVehicleModelChanging(string value);
    partial void OnPreferredVehicleModelChanged();
    partial void OnApptSetChanging(System.Nullable<bool> value);
    partial void OnApptSetChanged();
    partial void Onupsize_tsChanging(System.Data.Linq.Binary value);
    partial void Onupsize_tsChanged();
    partial void OnRowDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRowDateTimeChanged();
    #endregion
		
		public Contact()
		{
			this._DealerInventoryCICOs = new EntitySet<DealerInventoryCICO>(new Action<DealerInventoryCICO>(this.attach_DealerInventoryCICOs), new Action<DealerInventoryCICO>(this.detach_DealerInventoryCICOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this.OnContactIDChanging(value);
					this.SendPropertyChanging();
					this._ContactID = value;
					this.SendPropertyChanged("ContactID");
					this.OnContactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLNumber", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string DLNumber
		{
			get
			{
				return this._DLNumber;
			}
			set
			{
				if ((this._DLNumber != value))
				{
					this.OnDLNumberChanging(value);
					this.SendPropertyChanging();
					this._DLNumber = value;
					this.SendPropertyChanged("DLNumber");
					this.OnDLNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthdayYear", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> BirthdayYear
		{
			get
			{
				return this._BirthdayYear;
			}
			set
			{
				if ((this._BirthdayYear != value))
				{
					this.OnBirthdayYearChanging(value);
					this.SendPropertyChanging();
					this._BirthdayYear = value;
					this.SendPropertyChanged("BirthdayYear");
					this.OnBirthdayYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(1)", UpdateCheck=UpdateCheck.Never)]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateOrProvince", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string StateOrProvince
		{
			get
			{
				return this._StateOrProvince;
			}
			set
			{
				if ((this._StateOrProvince != value))
				{
					this.OnStateOrProvinceChanging(value);
					this.SendPropertyChanging();
					this._StateOrProvince = value;
					this.SendPropertyChanged("StateOrProvince");
					this.OnStateOrProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", DbType="NVarChar(25) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this.OnHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._HomePhone = value;
					this.SendPropertyChanged("HomePhone");
					this.OnHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeadSource", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string LeadSource
		{
			get
			{
				return this._LeadSource;
			}
			set
			{
				if ((this._LeadSource != value))
				{
					this.OnLeadSourceChanging(value);
					this.SendPropertyChanging();
					this._LeadSource = value;
					this.SendPropertyChanged("LeadSource");
					this.OnLeadSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeadOriginalDate", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> LeadOriginalDate
		{
			get
			{
				return this._LeadOriginalDate;
			}
			set
			{
				if ((this._LeadOriginalDate != value))
				{
					this.OnLeadOriginalDateChanging(value);
					this.SendPropertyChanging();
					this._LeadOriginalDate = value;
					this.SendPropertyChanged("LeadOriginalDate");
					this.OnLeadOriginalDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessPhone", DbType="NVarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string BusinessPhone
		{
			get
			{
				return this._BusinessPhone;
			}
			set
			{
				if ((this._BusinessPhone != value))
				{
					this.OnBusinessPhoneChanging(value);
					this.SendPropertyChanging();
					this._BusinessPhone = value;
					this.SendPropertyChanged("BusinessPhone");
					this.OnBusinessPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePhone", DbType="NVarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string MobilePhone
		{
			get
			{
				return this._MobilePhone;
			}
			set
			{
				if ((this._MobilePhone != value))
				{
					this.OnMobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._MobilePhone = value;
					this.SendPropertyChanged("MobilePhone");
					this.OnMobilePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNumber", DbType="NVarChar(25)", UpdateCheck=UpdateCheck.Never)]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebPage", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string WebPage
		{
			get
			{
				return this._WebPage;
			}
			set
			{
				if ((this._WebPage != value))
				{
					this.OnWebPageChanging(value);
					this.SendPropertyChanging();
					this._WebPage = value;
					this.SendPropertyChanged("WebPage");
					this.OnWebPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ContactNotes
		{
			get
			{
				return this._ContactNotes;
			}
			set
			{
				if ((this._ContactNotes != value))
				{
					this.OnContactNotesChanging(value);
					this.SendPropertyChanging();
					this._ContactNotes = value;
					this.SendPropertyChanged("ContactNotes");
					this.OnContactNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockNumber", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string StockNumber
		{
			get
			{
				return this._StockNumber;
			}
			set
			{
				if ((this._StockNumber != value))
				{
					this.OnStockNumberChanging(value);
					this.SendPropertyChanging();
					this._StockNumber = value;
					this.SendPropertyChanged("StockNumber");
					this.OnStockNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredVehicleType", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string PreferredVehicleType
		{
			get
			{
				return this._PreferredVehicleType;
			}
			set
			{
				if ((this._PreferredVehicleType != value))
				{
					this.OnPreferredVehicleTypeChanging(value);
					this.SendPropertyChanging();
					this._PreferredVehicleType = value;
					this.SendPropertyChanged("PreferredVehicleType");
					this.OnPreferredVehicleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredVehicleYear", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PreferredVehicleYear
		{
			get
			{
				return this._PreferredVehicleYear;
			}
			set
			{
				if ((this._PreferredVehicleYear != value))
				{
					this.OnPreferredVehicleYearChanging(value);
					this.SendPropertyChanging();
					this._PreferredVehicleYear = value;
					this.SendPropertyChanged("PreferredVehicleYear");
					this.OnPreferredVehicleYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredVehicleMake", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string PreferredVehicleMake
		{
			get
			{
				return this._PreferredVehicleMake;
			}
			set
			{
				if ((this._PreferredVehicleMake != value))
				{
					this.OnPreferredVehicleMakeChanging(value);
					this.SendPropertyChanging();
					this._PreferredVehicleMake = value;
					this.SendPropertyChanged("PreferredVehicleMake");
					this.OnPreferredVehicleMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredVehicleModel", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string PreferredVehicleModel
		{
			get
			{
				return this._PreferredVehicleModel;
			}
			set
			{
				if ((this._PreferredVehicleModel != value))
				{
					this.OnPreferredVehicleModelChanging(value);
					this.SendPropertyChanging();
					this._PreferredVehicleModel = value;
					this.SendPropertyChanged("PreferredVehicleModel");
					this.OnPreferredVehicleModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApptSet", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> ApptSet
		{
			get
			{
				return this._ApptSet;
			}
			set
			{
				if ((this._ApptSet != value))
				{
					this.OnApptSetChanging(value);
					this.SendPropertyChanging();
					this._ApptSet = value;
					this.SendPropertyChanged("ApptSet");
					this.OnApptSetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upsize_ts", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary upsize_ts
		{
			get
			{
				return this._upsize_ts;
			}
			set
			{
				if ((this._upsize_ts != value))
				{
					this.Onupsize_tsChanging(value);
					this.SendPropertyChanging();
					this._upsize_ts = value;
					this.SendPropertyChanged("upsize_ts");
					this.Onupsize_tsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowDateTime", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> RowDateTime
		{
			get
			{
				return this._RowDateTime;
			}
			set
			{
				if ((this._RowDateTime != value))
				{
					this.OnRowDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RowDateTime = value;
					this.SendPropertyChanged("RowDateTime");
					this.OnRowDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Contact_DealerInventoryCICO", Storage="_DealerInventoryCICOs", ThisKey="ContactID", OtherKey="CheckOutContactID")]
		public EntitySet<DealerInventoryCICO> DealerInventoryCICOs
		{
			get
			{
				return this._DealerInventoryCICOs;
			}
			set
			{
				this._DealerInventoryCICOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.Contact = this;
		}
		
		private void detach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.Contact = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vendors")]
	public partial class Vendor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VendorID;
		
		private string _VendorName;
		
		private string _VendorAddress;
		
		private string _VendorCity;
		
		private string _VendorStateOrProvince;
		
		private string _VendorPostalCode;
		
		private string _ContactPerson;
		
		private string _OfficeNumber;
		
		private string _CellNumber;
		
		private string _VendorNotes;
		
		private System.Nullable<System.DateTime> _InactiveDateTime;
		
		private System.Nullable<System.DateTime> _RowDateTime;
		
		private EntitySet<DealerInventoryCICO> _DealerInventoryCICOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVendorIDChanging(int value);
    partial void OnVendorIDChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnVendorAddressChanging(string value);
    partial void OnVendorAddressChanged();
    partial void OnVendorCityChanging(string value);
    partial void OnVendorCityChanged();
    partial void OnVendorStateOrProvinceChanging(string value);
    partial void OnVendorStateOrProvinceChanged();
    partial void OnVendorPostalCodeChanging(string value);
    partial void OnVendorPostalCodeChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnOfficeNumberChanging(string value);
    partial void OnOfficeNumberChanged();
    partial void OnCellNumberChanging(string value);
    partial void OnCellNumberChanged();
    partial void OnVendorNotesChanging(string value);
    partial void OnVendorNotesChanged();
    partial void OnInactiveDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnInactiveDateTimeChanged();
    partial void OnRowDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRowDateTimeChanged();
    #endregion
		
		public Vendor()
		{
			this._DealerInventoryCICOs = new EntitySet<DealerInventoryCICO>(new Action<DealerInventoryCICO>(this.attach_DealerInventoryCICOs), new Action<DealerInventoryCICO>(this.detach_DealerInventoryCICOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VendorID
		{
			get
			{
				return this._VendorID;
			}
			set
			{
				if ((this._VendorID != value))
				{
					this.OnVendorIDChanging(value);
					this.SendPropertyChanging();
					this._VendorID = value;
					this.SendPropertyChanged("VendorID");
					this.OnVendorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this.OnVendorNameChanging(value);
					this.SendPropertyChanging();
					this._VendorName = value;
					this.SendPropertyChanged("VendorName");
					this.OnVendorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorAddress", DbType="NVarChar(255)")]
		public string VendorAddress
		{
			get
			{
				return this._VendorAddress;
			}
			set
			{
				if ((this._VendorAddress != value))
				{
					this.OnVendorAddressChanging(value);
					this.SendPropertyChanging();
					this._VendorAddress = value;
					this.SendPropertyChanged("VendorAddress");
					this.OnVendorAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorCity", DbType="NVarChar(255)")]
		public string VendorCity
		{
			get
			{
				return this._VendorCity;
			}
			set
			{
				if ((this._VendorCity != value))
				{
					this.OnVendorCityChanging(value);
					this.SendPropertyChanging();
					this._VendorCity = value;
					this.SendPropertyChanged("VendorCity");
					this.OnVendorCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorStateOrProvince", DbType="NVarChar(255)")]
		public string VendorStateOrProvince
		{
			get
			{
				return this._VendorStateOrProvince;
			}
			set
			{
				if ((this._VendorStateOrProvince != value))
				{
					this.OnVendorStateOrProvinceChanging(value);
					this.SendPropertyChanging();
					this._VendorStateOrProvince = value;
					this.SendPropertyChanged("VendorStateOrProvince");
					this.OnVendorStateOrProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorPostalCode", DbType="NVarChar(255)")]
		public string VendorPostalCode
		{
			get
			{
				return this._VendorPostalCode;
			}
			set
			{
				if ((this._VendorPostalCode != value))
				{
					this.OnVendorPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._VendorPostalCode = value;
					this.SendPropertyChanged("VendorPostalCode");
					this.OnVendorPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="NVarChar(255)")]
		public string ContactPerson
		{
			get
			{
				return this._ContactPerson;
			}
			set
			{
				if ((this._ContactPerson != value))
				{
					this.OnContactPersonChanging(value);
					this.SendPropertyChanging();
					this._ContactPerson = value;
					this.SendPropertyChanged("ContactPerson");
					this.OnContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeNumber", DbType="NVarChar(255)")]
		public string OfficeNumber
		{
			get
			{
				return this._OfficeNumber;
			}
			set
			{
				if ((this._OfficeNumber != value))
				{
					this.OnOfficeNumberChanging(value);
					this.SendPropertyChanging();
					this._OfficeNumber = value;
					this.SendPropertyChanged("OfficeNumber");
					this.OnOfficeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNumber", DbType="NVarChar(255)")]
		public string CellNumber
		{
			get
			{
				return this._CellNumber;
			}
			set
			{
				if ((this._CellNumber != value))
				{
					this.OnCellNumberChanging(value);
					this.SendPropertyChanging();
					this._CellNumber = value;
					this.SendPropertyChanged("CellNumber");
					this.OnCellNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorNotes", DbType="NVarChar(MAX)")]
		public string VendorNotes
		{
			get
			{
				return this._VendorNotes;
			}
			set
			{
				if ((this._VendorNotes != value))
				{
					this.OnVendorNotesChanging(value);
					this.SendPropertyChanging();
					this._VendorNotes = value;
					this.SendPropertyChanged("VendorNotes");
					this.OnVendorNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InactiveDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> InactiveDateTime
		{
			get
			{
				return this._InactiveDateTime;
			}
			set
			{
				if ((this._InactiveDateTime != value))
				{
					this.OnInactiveDateTimeChanging(value);
					this.SendPropertyChanging();
					this._InactiveDateTime = value;
					this.SendPropertyChanged("InactiveDateTime");
					this.OnInactiveDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RowDateTime
		{
			get
			{
				return this._RowDateTime;
			}
			set
			{
				if ((this._RowDateTime != value))
				{
					this.OnRowDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RowDateTime = value;
					this.SendPropertyChanged("RowDateTime");
					this.OnRowDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendor_DealerInventoryCICO", Storage="_DealerInventoryCICOs", ThisKey="VendorID", OtherKey="CheckOutVendorID")]
		public EntitySet<DealerInventoryCICO> DealerInventoryCICOs
		{
			get
			{
				return this._DealerInventoryCICOs;
			}
			set
			{
				this._DealerInventoryCICOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.Vendor = this;
		}
		
		private void detach_DealerInventoryCICOs(DealerInventoryCICO entity)
		{
			this.SendPropertyChanging();
			entity.Vendor = null;
		}
	}
}
#pragma warning restore 1591
